Repository OkenHaha/react-blog, pull requests merged in 2025-02, with the labels that each got.

#245 Save article as Draft Feature (Backend)
  back-end/controllers/article.controller.js
  back-end/models/article.model.js
  back-end/routes/article.routes.js
Labels: enhancement, SWOC, level 3, IWCO2025, Hard

#247 Popup
  front-end/src/pages/popup.css
  front-end/src/pages/popup.html
  front-end/src/pages/popup.jsx
Labels: enhancement, good first issue, SWOC, level 1

#251 added privacy policy
  front-end/src/App.jsx
  front-end/src/components/Footer.jsx
  front-end/src/pages/PrivacyPolicy.jsx
Labels: documentation, enhancement, SWOC, level 1

#252 added achievement backend system
  back-end/app.js
  back-end/controllers/achievement.controller.js
  back-end/controllers/article.controller.js
  back-end/controllers/user.controller.js
  back-end/middleware/achievement.middleware.js
  back-end/models/achievement.model.js
  back-end/models/user.model.js
  back-end/routes/achievements.route.js
  back-end/routes/article.routes.js
Labels: enhancement, SWOC, level 3, IWCO2025, Hard

#253 Save Article as Draft (Frontend)
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/pages/AddarticlePage.jsx
  front-end/src/pages/DraftsPage.jsx
  front-end/vite.config.js
Labels: SWOC, level 3, IWCO2025, Hard

#262 Dark Mode in Add Article Page
  front-end/src/pages/AddarticlePage.jsx
Labels: enhancement, good first issue, SWOC, level 1, IWOC2025, Easy

#263 Lazy Loading Added
  front-end/src/App.jsx
  front-end/src/Utils/loader.jsx
  front-end/src/main.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#264 UI/UX Enhancement of ArticleList Page
  front-end/src/pages/ArticleList.jsx
Labels: enhancement, IWOC2025, Medium

#266 Added cursor trail
  front-end/src/components/CursorTrail.jsx
  front-end/src/index.css
  front-end/src/main.jsx
Labels: enhancement, SWOC, level 2, IWOC2025, Medium

#271 privacy policy page UI enhancement (Closes #260)
  front-end/src/pages/PrivacyPolicy.jsx
Labels: documentation, enhancement, IWOC2025, Medium

#272 Fixed the alignment of home page, Bug #261
  front-end/src/index.css
Labels: bug, enhancement, good first issue, SWOC, level 1

#273 added save for later functionality
  back-end/controllers/article.controller.js
  back-end/routes/article.routes.js
  front-end/src/components/SaveForLaterComp/SaveforLater.jsx
  front-end/src/components/SaveForLaterComp/SaveforlaterButton.jsx
  front-end/src/pages/Article.jsx
  front-end/src/pages/ProfilePage.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#274 Pagination
  back-end/app.js
  back-end/controllers/article.controller.js
  front-end/src/pages/ArticleList.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#279 UI for Creating Article Page
  front-end/src/pages/AddarticlePage.jsx
Labels: enhancement, SWOC, level 2, IWOC2025, Medium

#281 Added achievement system frontend
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/components/AchievementComp/AchievementComp.jsx
  front-end/src/pages/ProfilePage.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#277 About Page Design Update
  front-end/src/pages/About.jsx
  package.json
Labels: enhancement, IWOC2025, Hard

#283 Created `LICENSE`
  LICENSE
Labels: documentation, enhancement, SWOC, level 2

#287 Add article Button
  front-end/src/pages/ArticleList.jsx
Labels: bug, good first issue, SWOC, level 1, IWOC2025, Easy

#289 Spacing around the page
  back-end/app.js
  front-end/src/index.css
Labels: bug, good first issue, SWOC, level 1, IWOC2025, Easy

#286 fix: text color glitch in forgot password route
  front-end/src/components/ForgotPassword.jsx
Labels: bug, good first issue, SWOC, level 1

#285 save for later improvements
  front-end/src/components/ArticledetailsModal.jsx
  front-end/src/components/SaveForLaterComp/SaveforLater.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#295 fix: DOB glitch solved
  front-end/src/components/Navbar.jsx
Labels: bug, good first issue, SWOC, level 1

#296 feat: dynamic and new ui dashboard page
  front-end/package-lock.json
  front-end/package.json
  front-end/src/pages/Dashboard.jsx
Labels: bug, enhancement, SWOC, level 3

#297 Dark mode in comment
  front-end/src/pages/AddComment.jsx
Labels: enhancement, SWOC, level 1, IWOC2025, Easy

#301 added saveforlater comp
  back-end/controllers/user.controller.js
  front-end/src/components/ArticledetailsModal.jsx
  front-end/src/components/LikeArticles/LikeArticlesComp.jsx
  front-end/src/pages/ProfilePage.jsx
Labels: enhancement, SWOC, level 2, IWOC2025, Medium

#300 Follow user backend
  back-end/controllers/user.controller.js
  back-end/models/user.model.js
  back-end/routes/user.routes.js
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#308 addded pagination to the profile page
  front-end/src/components/paginatedComp/ProfilePaginatedComp.jsx
  front-end/src/pages/ProfilePage.jsx
  front-end/src/pages/prevarticlesectionBackup.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#310 Follow User Frontend
  back-end/controllers/user.controller.js
  front-end/src/pages/PublicProfile.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#311 Unfollow User Backend
  back-end/controllers/user.controller.js
  back-end/routes/user.routes.js
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#312 fixed the dashboard page
  back-end/controllers/article.controller.js
  back-end/routes/article.routes.js
  front-end/src/pages/Dashboard.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#318 Added Automated Contribution Certificate
  front-end/package-lock.json
  front-end/package.json
  front-end/src/pages/CertificateGenerator.jsx
  front-end/src/pages/Contributors.jsx
  package-lock.json
Labels: documentation, enhancement, SWOC, Hard

#323 fix: shorten the description of article in ui
  front-end/src/components/Articles.jsx
  front-end/src/components/SaveForLaterComp/SaveforLater.jsx
  front-end/src/pages/ArticleList.jsx
Labels: bug, good first issue, SWOC, level 1

#324 fix: added others label dropdown [ui]
  front-end/src/pages/AddarticlePage.jsx
  front-end/src/pages/ArticleList.jsx
Labels: bug, enhancement, good first issue, SWOC, level 1

#327 added images fixed achievement
  back-end/asset/Blogger.jpg
  back-end/asset/Reactor.jpg
  back-end/asset/Reader.jpg
  back-end/middleware/achievement.middleware.js
  back-end/models/achievement.model.js
  front-end/src/components/AchievementComp/AchievementComp.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#330 UI fixed of crads of about us page
  front-end/src/pages/About.jsx
  package-lock.json
Labels: enhancement, SWOC, level 2, IWOC2025, Medium

#334 saved for later without login
  front-end/src/App.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/pages/Article.jsx
  front-end/src/pages/SavedArticles.jsx
Labels: enhancement, SWOC, level 2, IWOC2025, Medium

#337 Profile Page UI/UX
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/LikeArticles/LikeArticlesComp.jsx
  front-end/src/pages/ProfilePage.jsx
  front-end/src/pages/SavedArticles.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#336 Show more articles
  front-end/src/pages/PublicProfile.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#335 Edit Article Dark
  front-end/src/pages/EditArticle.jsx
Labels: bug, good first issue, SWOC, level 1, IWOC2025, Easy

#343 Integrated Tidio Chatbot for Enhanced User Support & Engagement
  front-end/src/components/Tidio.jsx
  front-end/src/pages/About.jsx
  front-end/src/pages/ArticleList.jsx
  front-end/src/pages/Contributors.jsx
  front-end/src/pages/FAQ.jsx
  front-end/src/pages/Home.jsx
  front-end/src/pages/PublicProfile.jsx
Labels: enhancement, SWOC, level 3

#344 removed the base unnessary files
  package-lock.json
  package.json
Labels: bug, good first issue, SWOC, level 1

#350 fix: get started button in about page
  front-end/src/components/Centre.jsx
  front-end/src/pages/About.jsx
Labels: bug, enhancement, SWOC, level 1

#352 Frontend Implementation for User Reactions
  front-end/src/pages/Article.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#356 I have added streak feature backend
  back-end/controllers/streak.controller.js
  back-end/middleware/streak.middleware.js
  back-end/models/streak.model.js
  front-end/src/components/PaginatedArticle.jsx
  front-end/src/pages/PublicProfile.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#359 added animation in the auth modal
  front-end/src/components/Navbar.jsx
Labels: enhancement, SWOC, level 3, IWOC2025, Hard

#363 Enhanced Footer section
  front-end/src/components/Footer.jsx
Labels: enhancement, SWOC, level 2

#371 fix: added footer item nav to home
  front-end/src/components/Footer.jsx
Labels: enhancement, SWOC, level 1

#372 fix: added functionality to home buttons
  front-end/src/components/Centre.jsx
Labels: enhancement, SWOC, level 1

#373 Adding preloader
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/components/Preloader.css
  front-end/src/components/Preloader.jsx
Labels: enhancement, SWOC, level 2

#370 fix: added article item footer navigation
  front-end/src/components/Footer.jsx
  front-end/src/pages/AddarticlePage.jsx
Labels: bug, enhancement, SWOC, level 2

#378 Testimonals page
  front-end/src/components/Centre.jsx
Labels: enhancement, SWOC, level 2

#379 feat: navbar improved largely
  front-end/src/App.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/hooks/useTheme.js
Labels: enhancement, SWOC, level 3

#380 Feat: improved and add privacy policy and navigation
  front-end/src/App.jsx
  front-end/src/pages/PrivacyPolicy.jsx
Labels: enhancement, SWOC, level 2

#381 feat: implemented footer fix when no articles are there
  front-end/src/index.css
  front-end/src/pages/SavedArticles.jsx
Labels: enhancement, SWOC, level 1
