Repository OkenHaha/react-blog, pull requests merged in 2025-01, with the labels that each got.

#40 Edit profile
  back-end/.env
  back-end/app.js
  back-end/controllers/user.controller.js
  back-end/routes/user.routes.js
  front-end/src/App.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/pages/EditProfilePage.jsx
  front-end/src/pages/ProfilePage.jsx
Labels: enhancement, SWOC, level 3

#47 Making blogs 14
  back-end/app.js
  back-end/controllers/article.controller.js
  back-end/models/article.model.js
  back-end/models/user.model.js
  back-end/routes/article.routes.js
  front-end/src/components/AddComment.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/pages/AddArticle.jsx
  front-end/src/pages/Article.jsx
  front-end/src/pages/ArticleList.jsx
  front-end/src/pages/ProfilePage.jsx
Labels: enhancement, SWOC, level 2, level 3

#60 Added FAQ's in quickLink
  front-end/src/App.jsx
  front-end/src/components/Footer.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/pages/FAQ.jsx
Labels: enhancement, good first issue, SWOC, level 2

#62 Add Delete Article Functionality
  back-end/controllers/article.controller.js
  back-end/routes/article.routes.js
  front-end/src/pages/Article.jsx
Labels: bug, good first issue, SWOC, level 2, level 3

#63 fix: update redirect method after article deletion
  front-end/src/pages/Article.jsx
Labels: bug, enhancement, level 2

#64 Added Delete Article button with full functionality
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Articles.jsx
  front-end/src/components/Navbar.jsx
Labels: enhancement, SWOC, level 2, level 3

#73 Fixed the article-list page
  .env
  back-end/app.js
  back-end/controllers/article.controller.js
  back-end/models/article.model.js
  back-end/package-lock.json
  back-end/package.json
  back-end/vercel.json
  front-end/src/components/Articles.jsx
  front-end/src/components/Baselink.js
  front-end/src/pages/ArticleList.jsx
  front-end/src/pages/article_jsx_backup.txt
Labels: bug, enhancement, question, SWOC, level 2

#76 Enhance navbar UI
  front-end/src/App.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/pages/About.jsx
  front-end/src/pages/Article.jsx
  front-end/src/pages/ArticleList.jsx
  front-end/src/pages/EditProfilePage.jsx
  front-end/src/pages/FAQ.jsx
  front-end/src/pages/Home.jsx
  front-end/src/pages/NotFound.jsx
  front-end/src/pages/ProfilePage.jsx
Labels: enhancement, SWOC, level 1

#81 Implemented redux persit store
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/main.jsx
  front-end/src/store/authSlice.js
  front-end/src/store/store.js
Labels: enhancement, SWOC, level 2

#84 Fixed editing and adding of articles thumbnails
  back-end/controllers/article.controller.js
  back-end/routes/article.routes.js
  front-end/src/components/Baselink.js
  front-end/src/pages/AddArticle.jsx
  front-end/src/pages/ArticleList.jsx
  front-end/src/pages/EditArticle.jsx
  front-end/src/pages/ProfilePage.jsx
Labels: bug, enhancement, level 3

#87 Implement a Common Footer for All Pages
  front-end/src/App.jsx
  front-end/src/components/Footer.jsx
  front-end/src/pages/Home.jsx
Labels: enhancement, good first issue, SWOC

#89 Delete User Backend added
  back-end/Utils/otpgenerate.js
  back-end/app.js
  back-end/controllers/user.controller.js
  back-end/routes/user.routes.js
Labels: enhancement, SWOC, level 3

#91 Added like feature to a articles
  back-end/controllers/article.controller.js
  back-end/models/article.model.js
  back-end/models/user.model.js
  back-end/routes/article.routes.js
Labels: enhancement, SWOC, level 3

#96 Handle Thumbnail as File Type in AddArticle Component
  front-end/src/components/Baselink.js
  front-end/src/components/Navbar.jsx
  front-end/src/pages/AddArticle.jsx
Labels: bug, enhancement, SWOC, level 2

#97 Add Edit and Delete Buttons for User's Own Articles
  back-end/api/index.js
  front-end/src/App.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/pages/AddArticle.jsx
  front-end/src/pages/Article.jsx
Labels: enhancement, SWOC, level 3

#98 Profile page enhancement
  front-end/src/pages/ProfilePage.jsx
Labels: enhancement, SWOC, level 1

#103 Enhanced the artilcle listing page
  back-end/app.js
  front-end/src/components/Baselink.js
  front-end/src/pages/AddArticle.jsx
  front-end/src/pages/ArticleList.jsx
Labels: enhancement, good first issue, SWOC

#105 Added Frontend for Like
  back-end/controllers/article.controller.js
  back-end/controllers/user.controller.js
  front-end/src/components/LikeButton.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/pages/Article.jsx
  front-end/src/pages/ArticleList.jsx
Labels: enhancement, good first issue, SWOC, level 1

#104 Add ApiError utility for standardized error handling
  back-end/Utils/Api.Error.js
  desktop.ini
Labels: enhancement, SWOC, level 1

#106 Added sorting and and searching of article
  back-end/models/article.model.js
  front-end/src/pages/ArticleList.jsx
Labels: bug, enhancement, SWOC, level 2

#110 Added Contributors List in README.md
  README.md
Labels: documentation, enhancement, good first issue, SWOC

#111 add response utility #107
  back-end/Utils/Api.Response.js
Labels: enhancement, SWOC, level 2

#113 Delete user frontend
  front-end/src/components/Baselink.js
  front-end/src/main.jsx
  front-end/src/pages/ProfilePage.jsx
  package-lock.json
  package.json
Labels: enhancement, SWOC, level 2

#114 Enhancement of edit profile page
  front-end/src/pages/EditProfilePage.jsx
Labels: bug, enhancement, SWOC, level 2

#117 Feature/mission vision values #112
  front-end/src/assets/mission.jpg
  front-end/src/assets/values.avif
  front-end/src/assets/vision.avif
  front-end/src/components/Centre.jsx
Labels: enhancement, good first issue, SWOC

#120 tried fixing dark mode in article and about page
  front-end/src/pages/About.jsx
  front-end/src/pages/Article.jsx
Labels: bug, enhancement, good first issue, SWOC

#128 Added error handling in db.js
  back-end/db.js
Labels: enhancement, SWOC, level 1

#127 edit article bug fixed
  front-end/package-lock.json
  front-end/src/pages/Article.jsx
Labels: bug, enhancement, SWOC, level 1

#131 Added backend for forgot password
  back-end/Utils/otpgenerate.js
  back-end/controllers/user.controller.js
  back-end/routes/user.routes.js
Labels: enhancement, SWOC, level 3

#133 Update README.md with .env setup details.
  README.md
Labels: documentation, good first issue, SWOC, level 1

#132 Added image file upload in edit profile
  back-end/controllers/user.controller.js
  back-end/routes/user.routes.js
  front-end/src/components/Baselink.js
  front-end/src/pages/EditProfilePage.jsx
Labels: enhancement, SWOC, level 3

#137 Added stargazer and forkers info in README.md
  README.md
Labels: documentation, enhancement, good first issue, SWOC, level 1

#139 Add Popup Confirmation for Deleting Articles
  front-end/src/components/AlertDialog.jsx
  front-end/src/pages/Article.jsx
Labels: enhancement, good first issue, SWOC

#153 Fixed dark mode bug
  front-end/src/components/Centre.jsx
  front-end/tailwind.config.cjs
Labels: bug, enhancement, good first issue, SWOC

#154 Add theme toggle theme button in Navbar for mobile view
  front-end/src/components/Baselink.js
  front-end/src/components/Navbar.jsx
Labels: bug, enhancement, good first issue, SWOC

#156 [Feature]: Contributors page
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/components/Centre.jsx
  front-end/src/components/Footer.jsx
  front-end/src/components/contributors/ContributorsLink.jsx
  front-end/src/components/contributors/contribution.js
  front-end/src/pages/Contributors.jsx
Labels: enhancement, good first issue, SWOC, level 1

#155 Updated ui for footer
  front-end/package-lock.json
  front-end/src/assets/github.svg
  front-end/src/components/Footer.jsx
Labels: enhancement, good first issue, SWOC

#158 Added cursor trails
  front-end/package-lock.json
  front-end/package.json
  front-end/src/index.css
  front-end/src/main.jsx
Labels: enhancement, SWOC, level 2

#159 Add Search Bar
  front-end/src/App.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/pages/SearchPage.jsx
Labels: enhancement, SWOC, level 2

#160 Added no article UI
  front-end/src/assets/noarticle.png
  front-end/src/pages/ArticleList.jsx
  tailwind.config.js
Labels: bug, SWOC, level 2

#162 Added loader while creating article
  front-end/src/Utils/loader.css
  front-end/src/Utils/loader.jsx
  front-end/src/pages/AddArticle.jsx
Labels: enhancement, SWOC, level 2

#164 Fixing add comment and article article page styling
  back-end/controllers/article.controller.js
  back-end/models/article.model.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/pages/Article.jsx
Labels: enhancement, good first issue, SWOC, level 2

#165 Remove SearchPage component and related Navbar link
  front-end/src/components/Footer.jsx
  front-end/src/components/Navbar.jsx
  front-end/src/pages/SearchPage.jsx
Labels: enhancement, good first issue, SWOC

#170 Enhance profile and edit profile pages with dynamic image handling and Improved UI Layout
  front-end/dist/assets/blog.e6422f03.png
  front-end/dist/assets/close.945782e8.svg
  front-end/dist/assets/github.1ad80677.svg
  front-end/dist/assets/index.6e3495c4.css
  front-end/dist/assets/index.c3dca60d.js
  front-end/dist/assets/menu.e0613cf3.svg
  front-end/dist/assets/mission.cdd40102.jpg
  front-end/dist/assets/noarticle.29b5e3a7.png
  front-end/dist/assets/read-blog.f7531dd5.jpg
  front-end/dist/assets/values.70f7ec9f.avif
  front-end/dist/assets/vision.0555e7a5.avif
  front-end/dist/assets/write-blog.3595c09d.jpg
  front-end/dist/images/blog1.jpeg
  front-end/dist/images/blog2.jpeg
  front-end/dist/images/blog3.jpeg
  front-end/dist/index.html
  front-end/dist/vite.svg
  front-end/src/pages/EditProfilePage.jsx
  front-end/src/pages/ProfilePage.jsx
Labels: enhancement, SWOC, level 2

#178 Added tags in articles, searching by tags
  back-end/controllers/article.controller.js
  back-end/controllers/user.controller.js
  back-end/models/article.model.js
  back-end/routes/article.routes.js
  front-end/package-lock.json
  front-end/src/components/Articles.jsx
  front-end/src/components/Baselink.js
  front-end/src/pages/AddArticle.jsx
  front-end/src/pages/ArticleList.jsx
Labels: enhancement, SWOC, level 2

#180 changed-ui-of-faq-box
  front-end/src/pages/FAQ.jsx
Labels: enhancement, good first issue, SWOC, level 1

#181 🛠️ Feat : Github Actions added
  .github/workflows/auto-comment.yml
Labels: documentation, enhancement, SWOC

#183 Fix Delete button and add delete confirmation modal to Article component
  front-end/src/pages/Article.jsx
Labels: bug, documentation, SWOC, level 2

#190 Changed the logo and added steps to contribute to the website
  back-end/api/index.js
  back-end/db.js
  back-end/package-lock.json
  back-end/package.json
  front-end/index.html
  front-end/public/download.png
  front-end/src/components/Centre.jsx
Labels: bug, documentation, enhancement, good first issue, SWOC

#195 UI-Enhancement-Edit-Article
  front-end/src/pages/EditArticle.jsx
Labels: enhancement, SWOC, level 2

#196 Added Categories to articles
  front-end/src/pages/AddArticle.jsx
  front-end/src/pages/ArticleList.jsx
Labels: enhancement, good first issue, SWOC, level 2

#194 Updated Footer
  front-end/dist/assets/blog-CFnBPB-Q.png
  front-end/dist/assets/close.945782e8.svg
  front-end/dist/assets/github.1ad80677.svg
  front-end/dist/assets/index-fcqxFfij.css
  front-end/dist/assets/index-kpuegrC0.js
  front-end/dist/assets/index.4500d18e.css
  front-end/dist/assets/index.ff908a1e.js
  front-end/dist/assets/menu.e0613cf3.svg
  front-end/dist/assets/mission-Dc-O1fF_.jpg
  front-end/dist/assets/noarticle-BJxS4Uoj.png
  front-end/dist/assets/read-blog-Dfdbsgkg.jpg
  front-end/dist/assets/values-DmY0X_Mx.avif
  front-end/dist/assets/vision-DYlrP8Bg.avif
  front-end/dist/assets/write-blog-HtevdZXS.jpg
  front-end/dist/download.png
  front-end/dist/index.html
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Centre.jsx
  front-end/src/components/Footer.jsx
Labels: enhancement, good first issue, SWOC

#197 Comment Added Successfully
  back-end/controllers/article.controller.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/pages/AddComment.jsx
  front-end/src/pages/Article.jsx
Labels: bug, enhancement, SWOC, level 3

#202 Added a dashboard page
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/pages/Dashboard.jsx
  front-end/src/pages/ProfilePage.jsx
Labels: enhancement, SWOC, level 2

#203 Improved add comment button
  front-end/src/pages/Article.jsx
Labels: enhancement, good first issue, SWOC, level 1

#204 Displayed total comments
  back-end/controllers/article.controller.js
  back-end/models/user.model.js
  front-end/src/pages/ProfilePage.jsx
Labels: bug, SWOC, level 2

#205 Update
  front-end/.gitignore
  front-end/src/components/Centre.jsx
  front-end/src/components/Footer.css
  front-end/src/components/Footer.jsx
  front-end/src/index.html
  package-lock.json
  package.json
Labels: enhancement, good first issue, SWOC, level 1

#206 added 2 postman collections (user and article)
  Articles.postman_collection.json
  User.postman_collection.json
Labels: documentation, enhancement, SWOC, level 3

#207 Added loader while getting article
  front-end/src/Utils/loader.jsx
  front-end/src/pages/Article.jsx
Labels: bug, SWOC, level 2

#215 Email-Templates for Signup, Delete User, Forgot Password
  back-end/Utils/EmailTemplates.js
  back-end/Utils/otpgenerate.js
Labels: documentation, enhancement, SWOC, level 2

#218 Adding logo
  front-end/package-lock.json
  front-end/src/assets/Logo1.png
  front-end/src/assets/logo.png
  front-end/src/components/Navbar.jsx
Labels: enhancement, good first issue, SWOC, level 1

#221 added save as later and draft
  back-end/controllers/article.controller.js
  back-end/models/article.model.js
  back-end/models/user.model.js
  back-end/routes/article.routes.js
Labels: enhancement, SWOC, level 3

#223 Added markdown support
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/pages/AddarticlePage.jsx
  front-end/src/pages/Article.jsx
  front-end/src/pages/ArticleList.jsx
Labels: enhancement, SWOC, level 2

#225 Get User Profile Backend
  back-end/controllers/user.controller.js
  back-end/routes/user.routes.js
Labels: enhancement, SWOC, level 3

#232 404 Page Implementation
  front-end/src/App.jsx
  front-end/src/pages/Error404.jsx
Labels: enhancement, SWOC, level 2

#233 Profile Page for Any User - Frontend
  back-end/controllers/user.controller.js
  front-end/src/App.jsx
  front-end/src/pages/Article.jsx
  front-end/src/pages/PublicProfile.jsx
Labels: enhancement, SWOC, level 2

#235 Liked Article Bug Fix
  front-end/src/pages/ProfilePage.jsx
Labels: bug, SWOC, level 2

#236 Article Sharing Feature
  front-end/src/pages/Article.jsx
  front-end/src/pages/shareBtn.css
Labels: enhancement, SWOC, level 2

#244 added circular progress to scroll to button
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Baselink.js
  front-end/src/components/ScrollToTop.jsx
Labels: enhancement, good first issue, SWOC, level 1

#241 Most Liked, Oldest, Latest Articles Filter
  front-end/src/pages/ArticleList.jsx
Labels: enhancement, SWOC, level 3, IWCO2025, Hard

#240 Added level system
  back-end/controllers/article.controller.js
  back-end/controllers/user.controller.js
  back-end/models/level.model.js
  back-end/models/user.model.js
  front-end/src/pages/ProfilePage.jsx
Labels: enhancement, SWOC, level 2
